
package JNP_1A5b2wor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ObjectService", targetNamespace = "http://medianews.vn/", wsdlLocation = "http://203.162.10.109:8080/JNPWS/ObjectService?wsdl")
public class ObjectService_Service
    extends Service
{

    private final static URL OBJECTSERVICE_WSDL_LOCATION;
    private final static WebServiceException OBJECTSERVICE_EXCEPTION;
    private final static QName OBJECTSERVICE_QNAME = new QName("http://medianews.vn/", "ObjectService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://203.162.10.109:8080/JNPWS/ObjectService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OBJECTSERVICE_WSDL_LOCATION = url;
        OBJECTSERVICE_EXCEPTION = e;
    }

    public ObjectService_Service() {
        super(__getWsdlLocation(), OBJECTSERVICE_QNAME);
    }

    public ObjectService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), OBJECTSERVICE_QNAME, features);
    }

    public ObjectService_Service(URL wsdlLocation) {
        super(wsdlLocation, OBJECTSERVICE_QNAME);
    }

    public ObjectService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OBJECTSERVICE_QNAME, features);
    }

    public ObjectService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ObjectService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ObjectService
     */
    @WebEndpoint(name = "ObjectServicePort")
    public ObjectService getObjectServicePort() {
        return super.getPort(new QName("http://medianews.vn/", "ObjectServicePort"), ObjectService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ObjectService
     */
    @WebEndpoint(name = "ObjectServicePort")
    public ObjectService getObjectServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://medianews.vn/", "ObjectServicePort"), ObjectService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OBJECTSERVICE_EXCEPTION!= null) {
            throw OBJECTSERVICE_EXCEPTION;
        }
        return OBJECTSERVICE_WSDL_LOCATION;
    }

}
